### ISSUE TITLE
how to get the list of the symbols_ without Evaluate

### ISSUE THREAD

**Issue by zhongjingjogy** [nickgammon/parser#1]
Mr. Gammon:

I'm about to implement a simple symbolic computation function based on your parser. One problem I'm facing is that I do not want to evaluate the expression until all the symbols have been set manually. Here follows what I had tried. 

I implement a new Class Expr, which contains a data member map<string, double> _symbols as well as an object of Parser parser. In the constructor of Expr with a string as input, the input string will always treated by parser.Evaluate. And an Evaluate function for Expr is also implemented, which will always check whether the variables in Expr._symbols are the same as the parser.symbols_. If not,  the Expr.Evaluate will fail.

Things go quite smoothly, until the input string that implies division operation will raise exception as following
/*
terminate called after throwing an instance of 'std::runtime_error'
  what():  Divide by zero
Aborted (core dumped)
*/

Do you have any suggestion for this problem? 

Thanks

Zhong Jing

**Comment by nickgammon** [comment]
Can you post code that demonstrates this problem?

**Comment by zhongjingjogy** [comment]
Yes, it's my pleasure. The symbolic expression that I want to parse come following:

Parse p("exp((x_AL_x_CU_(AL_ALCU0_0 + AL_ALCU0_1_T + AL_ALCU0_2_T_log(T)) + x_AL_x_SI_(AL_ALSI0_0 + AL_ALSI0_1_T + AL_ALSI0_2_T_log(T)) + x_AL_(AL_AL0_0 + AL_AL0_1_T + AL_AL0_2_T_log(T)) + x_CU_(AL_CU0_0 + AL_CU0_1_T + AL_CU0_2_T_log(T)) + x_SI_(AL_SI0_0 + AL_SI0_1_T + AL_SI0_2_T_log(T)))/(R_T))/(R_T)");

As I do something like
    p.Evaluate()
then I got the error. And I have managed to figure out the problem, which is caused by the division operation on R*T. Since I haven't assigned any values to the Parser object, all the symbols will be automatically set to be zero. So evaluation will always fail when I try to do it without assignment.

In my case, the division operations will be always carried on R*T. So I have resolve it by presetting the values for R and T, and it works.

Thanks for your time.

**Comment by nickgammon** [comment]
I am glad you sorted it out. You can, of course, assign values to symbols before calling Evaluate, although since they default to zero, that won't stop a "divide by zero" error.
